---
- hosts: webserver
  become: yes
  tasks:
  - name: install java in ubuntu node
    apt: 
     name: "{{javapackageforubuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: install java in RedHat node
    yum:
     name: "{{javapackageforredhat}}"
     state: present
    when: ansible_os_family =="RedHat"
