---
- hosts: webserver
  become: yes
  tasks:
  - name: i want install webserver on ubuntu node only
    apt:
     name: "{{webserverpackforubuntu}}"
     state: present
    when: ansible_os_family =='Debian'

  - name: i want start webserver on ubuntu node
    service:
     name: "{{webserverpackforubuntu}}"
     state: started
    when: ansible_os_family =='Debian'


  - name: i want install webserver on RedHat node only
    yum:
     name: "{{webserverpackforRedHat}}"
     state: present
    when: ansible_os_family =='RedHat'
  
  - name: i want start webserver on RedHat node 
    service:
     name: "{{webserverpackforRedHat}}"
     state: started
    when: ansible_os_family =='RedHat'